version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t jorgepi/nodejs_webserver:1.0 . 
  test:
    machine: true
    steps:
      - checkout
      - run: docker build -t jorgepi/nodejs_webserver:1.0 .
      - run: docker run -it --name app1 jorgepi/nodejs_webserver:1.0 npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
