version: 2
jobs:
  build:
    docker:
      — image: node:7.10
    working_directory: /app
    steps:
      — checkout
      - run: 
        name: npm-install
        command: 'npm install'
      — run: 
        name: npm-test
        command: 'npm test'
